[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[metadata]
name = "flask_protobuf"
version = "0.1.3"
description = "Flask-Protobuf is a Python package that provides integration between Flask and Protocol Buffers (protobuf). It allows you to easily handle incoming protobuf messages in your Flask application."
author = "Jerick Gutierrez"
license = "MIT"
keywords = ["flask", "protobuf", "google", "protocol buffers"]
url = "https://github.com/Mackhintoshi/Flask-Protobuf"
long_description = """
Flask-Protobuf is a Python package that provides integration between Flask and Protocol Buffers (protobuf). It allows you to easily handle incoming protobuf messages in your Flask application.

Please see the [GitHub repository](https://github.com/Mackhintoshi/Flask-Protobuf) for more information and usage examples.
"""

[options]
packages = ["flask_protobuf"]
install_requires = ["Flask>=2.3.2", "protobuf>=3.17.3"]

flask_protobuf = ["README.md"]
